# Generated by Django 4.2.2 on 2023-06-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('title',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/docs', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='news',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='media/news', verbose_name='Файл'),
        ),
    ]
